### ISSUE TITLE
[수정] 날짜 구분선 보여주는 방식 바꾸기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#19]
## 작업할 내용
> 이전 채팅과 현재 채팅의 날짜를 비교하여 다를 때에만 사이에 날짜 구분선을 렌더링한다.

## todos
- [x] 데이터 구조 초기에 했던대로 다시 바꾸기
- [x] 날짜 비교하는 삼항연산자 or 변수 만들기
- [x] 결과에 따라 구분선 렌더링하기
- [x] 테스트

**Comment by aemaaeng** [comment]
`Array.prototype.map()` 메소드에서 리스트의 각 요소를 어떻게 비교하느냐가 관건이었다. 세 번째 인자가 원본 배열을 받는 것을 알게 되어서 세 번째 인자와 두 번째 인자 인덱스를 이용해서 앞 뒤 요소의 날짜를 비교해주는 식으로 구현했다.
