### ISSUE TITLE
[개선] next.js 13으로 마이그레이션

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#26]
## 작업할 내용
> next.js 13으로 마이그레이션한다

## 작업 계기
- 기존 React, TypeScript로 작업 시 큰 크기의 json 데이터를 매번 fetch로 불러오는 것이 부담스러웠다.
  - next.js 사용 시 간단한 API 구축 가능
  - 페이지가 렌더링될 때마다 `data.json`을 불러오는 것이 아니라 필요할 때에만 서버에 요청을 보내 데이터를 받아올 수 있다.
  - 필요한 경우 캐싱 가능 (더 찾아봐야 함)
- 이미지 최적화 작업의 번거로움
  - next/image로 해결 가능 (스타일링이 까다로운 게 단점)

## todos
- [x] next.js 셋업
- [x] `data.json` 전처리 작업
- [x] API Route로 간단한 API 만들기 
  - [x] 날짜 목록을 받아오는 `/api/list`, 각 날짜에 해당하는 채팅 데이터를 받아오는 `/api/chats/[id]` 
- [x] 스타일링 초기 작업
  - [x] styled-components `registry.tsx` 작업하기
- [x] 기존 코드 지우기
