### ISSUE TITLE
[기능] 리스트에서 미디어 파일 여부 보여주기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#35]
## 작업할 내용
> 날짜 리스트에서 채팅에 미디어가 포함되어 있는지 아이콘으로 미리 보여주기

## todos
- [x] 해당 날짜의 채팅에 포함된 미디어 파일의 종류를 보내주는 api 작성하기 
- [x] 종류에 따라 날짜 옆에 아이콘 표시하기 
- [x] `ListItem` 컴포넌트 grid로 보여주기
- [x] `ListItem` 컴포넌트 제목 hover 시 밑줄 애니메이션
