### ISSUE TITLE
[UI/UX] 루트 페이지 스타일링 

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#38]
## 작업할 내용
> 루트 페이지에 스타일을 적용한다 

## todos
- [x] 피그마로 디자인
- [x] 스타일 입히기 
- [x] 타이핑 이펙트 훅 초기 로직 구성하기 
  - 참고: https://gurtn.tistory.com/168, https://velog.io/@stormtrooper/Next.js-typing-animation-Blog5
- [x] 여러 단어를 쓰고 지울 수 있도록 로직 발전시키기 
- [x] 모바일 반응형 (글자 크기만 조절하기)
