### ISSUE TITLE
[수정] 이미지 layout shift 해결하기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#42]
## 작업할 내용
> 이미지 layout shift 해결하기, 이미지 불러올 때 공백 대신 블러효과 이미지가 보이도록 하기

## Todos
- [x] 원인 파악하기
  - 이미지의 사이즈에 맞게 높이가 자동으로 적용되게 해놓았음. 높이가 지정되지 않아서 layout shift가 발생하는 것 같음.. 
- [x] 해결방안 떠올리기
  - `plaiceholder`로 base64 주소를 만들 때 이미지 크기 정보도 같이 받아와 next/image 컴포넌트에 `width`, `height` 값으로 지정한다.
- [x] 동적 이미지 -> `blurDataURL`을 동적으로 생성해야 함
  - [x] `sharp` 라이브러리 찾아보기
  - [x] `plaiceholder` 라이브러리 적용하기
- [x] 렌더링 테스트
