### ISSUE TITLE
[수정] styled-components에서 module.css로 옮기기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#46]
## 작업할 내용
> styled-components에서 module.css로 css 스타일링을 옮긴다

## 작업 배경
issue #42 에서 `plaiceholder` 라이브러리 적용을 위해 함수를 작성함. 
함수는 이미지 파일을 불러와 버퍼를 생성하고 그 버퍼를 기반으로 base64URL을 생성하는 방식으로 동작함.
`public` 폴더에서 정적 이미지 파일을 불러올 때 node.js의 fs module을 써야했는데 node.js의 모듈은 서버 컴포넌트에서만 사용 가능하다는 걸 알게 됨. 브라우저에서는 동작 X  

`styled-components` 내부에서 `React.createContext()`를 사용하고 있어 클라이언트 컴포넌트로 쓰지 않으면 오류가 발생했음.
`plaiceholder`를 적용하려 했던 부분의 상위 컴포넌트 또한 `styled-components`를 쓰고 있어 전부 클라이언트 컴포넌트로 작성되어 있었음.
`plaiceholder` 라이브러리 적용도 불가능했을 뿐더러 서버 컴포넌트로 쓸 수 있는 것도 클라이언트 컴포넌트로 써야했기에 Next.js의 사용 목적과 충돌한다고 판단하여 module.css로 스타일링을 옮기기로 결정함.

## todos
- [x] module.css로 옮기기
- [x] styled-components 제거
- [x] `registry.tsx` 및 관련 코드 삭제
- [x] `next.config.js` 수정
