### ISSUE TITLE
[수정] 에러 페이지 만들기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#49]
## 작업할 내용
> 에러 페이지 만들기

## todos
- [x] 생길 수 있는 예외 상황 생각해보기
  - [x] url에 잘못된 경로가 들어온 경우
  - [x] `chats/YY-MM-DD`에서 유효한 날짜가 아니라 채팅 데이터를 받아오지 못했을 때
- [x] `not-found.tsx` 작성
  - [x] 스타일링
- [x] 적용
