### ISSUE TITLE
[UI/UX] 대화 내용 분 단위로 묶어서 보여주기

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#5]
## 작업할 내용
> 대화 내용 분 단위로 묶어서 보여준다.

## todos
- [x] 데이터 내 시간 KST로 변환하기
- [x] 분 단위로 grouping하는 함수 만들기
- [x] 프로필 사진, 이름 영역 컴포넌트 만들기
- [x] Bubbles 컴포넌트랑 묶어서 렌더링하기
- [x] 마지막 말풍선은 디자인 다르게 하기
- [x] 시간 hh:mm 형식으로 렌더링하기

## reference
<img width="350" alt="image" src="https://user-images.githubusercontent.com/78579776/222903935-d7795fae-ecfa-431f-a91d-7dca7d01839d.png">
