### ISSUE TITLE
[기능] 키워드 검색 기능

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#56]
## 작업할 내용
> 키워드가 포함된 채팅 날짜를 검색할 수 있는 기능을 추가한다

## todos
- [x] 디자인 구상
  - 참고 디자인: 스포티파이 pc 
  - <img width="690" alt="image" src="https://github.com/aemaaeng/universe-message-backup/assets/78579776/f53f648b-c13f-4228-92c5-acd70ac72797">
  - <img width="401" alt="image" src="https://github.com/aemaaeng/universe-message-backup/assets/78579776/13a2004f-b932-4565-8e5a-7196d1a6d5fe">
- [x] 컴포넌트 모양 구현
- [x] 키워드를 받아 해당 키워드가 포함된 채팅 날짜와 문장을 리턴하는 api 구상하기
- [x] api 구현
- [x] 상호작용 적용
- [x] 에러 핸들링
  - [x] 빈 키워드 validation 
  - [x] 검색 결과가 없을 경우
- [x] 반응형 디자인
- [x] 검색 결과에서 검색어 하이라이팅, 참고: https://velog.io/@suyeonme/텍스트-하이라이팅
