### ISSUE TITLE
[개선] 이미지 확장자 webp로 변경

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#6]
## 작업할 내용
> 이미지 확장자를 webp로 변경한다.

## todos
- [x] 테스트용 데이터 내 이미지 확장자 webp로 변경하기
- [x] 리소스 용량 비교해보기 (현재 7.7mb -> 5.7mb로 줄어들었음)
- [x] 확연하게 줄어든다면 전부 webp로 변환하기
