### ISSUE TITLE
[개선] 검색 결과 페이지 분리

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#64]
## 작업할 내용
> 검색 후 채팅 내용을 보고 뒤로가기를 하면 검색 결과가 사라짐. 검색 결과 페이지를 따로 분리하여 이 현상을 개선한다. 

## todos
- [x] `search` 페이지 만들기 
- [x] `useSearch` 훅으로 리팩토링
- [x] 기존 list 페이지에서 로직 빼내기
- [x] 스타일링 (+반응형)
- [x] 검색 결과가 없는 경우 다루기
