### ISSUE TITLE
[기능] 리스트 뷰, 그리드 뷰로 선택할 수 있는 기능

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#73]
## 작업할 내용
> 리스트 뷰, 그리드 뷰로 선택해 볼 수 있도록 한다. 

## todos
- [ ] 그리드 뷰 상태의 `ListItem` 컴포넌트 피그마 디자인
- [ ] 그리드 뷰 상태 `ListItem` 컴포넌트 구현
  - [ ] 서버에서 미디어 파일 포함 여부 데이터를 보내줄 때 이미지가 있는 경우 그 파일 경로도 같이 보내도록 하기
  - [ ] 동영상, 음성일 경우 다른 아이콘으로 대체해서 보여주기
  - [ ] 텍스트만 있을 경우 햄스터 이모지 표시해서 보여주기
- [ ] 뷰 선택할 수 있는 버튼 만들기 (기본값: 리스트 뷰)
- [ ] 클릭에 따라 뷰 변경되도록 기능 구현하기
