### ISSUE TITLE
[UI/UX] 리스트 컴포넌트 썸네일 추가

### ISSUE THREAD

**Issue by aemaaeng** [aemaaeng/universe-message-backup#74]
## 작업할 내용
> 날짜별 리스트 각 요소 좌측에 썸네일을 표시한다. 

## todos
**썸네일 영역에 보여줄 것**
- [x] 이미지 -> 이미지 썸네일을 보여준다.
- [x] 동영상, 음성 -> 둘 중 하나 아이콘으로 대체한다.
- [x] 텍스트만 -> 이모지를 보여준다. 

**서버 작업**
- [x] 이미지가 있는 경우 이미지 경로를 함께 리턴한다.
